insoh/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('vehiclemanager.urls')),
    path('admin/', admin.site.urls),
]

vehiclemanager/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('new', views.add_vehicle, name='add_vehicle'),
    path('edit/<int:vehicle_id>/', views.edit_vehicle, name='edit_vehicle'),
    path('delete/<int:vehicle_id>/', views.delete_vehicle, name='delete_vehicle'),
]

vehiclemanager/models.py
from django.db import models


class Vehicle(models.Model):
    id = models.IntegerField(unique=True, null=False, blank=False, primary_key=True, verbose_name="Numer ID")
    name = models.CharField(max_length=50, verbose_name="Nazwa pojazdu")

    @property
    def battery_number(self):
        batteries = Battery.objects.filter(vehicle=self)
        active_count = batteries.filter(is_on=True).count()
        all_count = batteries.count()

        return f"{active_count}/{all_count}"

    def __str__(self):
        return self.name

    def add_batteries(self, num):
        for n in range(num):
            Battery.create(vehicle=self)


class Battery(models.Model):
    battery_number = models.IntegerField(null=False, blank=False, verbose_name="Numer baterii")
    battery_id = models.IntegerField(null=False, blank=False)
    vehicle = models.ForeignKey(Vehicle, on_delete=models.CASCADE)
    is_on = models.BooleanField(default=True, verbose_name="Włączona")

    class Meta:
        verbose_name_plural = "batteries"

    @classmethod
    def create(cls, vehicle, is_on=True):
        highest_number = Battery.objects.filter(vehicle=vehicle).order_by('battery_number').last()
        highest_id = Battery.objects.filter(vehicle=vehicle).order_by('battery_id').last()
        b_number = highest_number.battery_number + 1 if highest_number else 1
        b_id = highest_id.battery_id + 2 if highest_id else 5

        b = Battery(vehicle=vehicle, is_on=is_on, battery_number=b_number, battery_id=b_id)
        b.save()

vehiclemanager/forms.py
from django.forms import ModelForm, IntegerField
from .models import Vehicle


class VehicleForm(ModelForm):
    batteries = IntegerField(label="Liczba baterii")

    class Meta:
        model = Vehicle
        fields = ['id', 'name', 'batteries']


class VehicleEditForm(ModelForm):
    class Meta:
        model = Vehicle
        fields = ['name']

vehiclemanager/views.py
from django.shortcuts import render, get_object_or_404
from django.forms import inlineformset_factory
from django.http import HttpResponseRedirect
from .models import Vehicle, Battery
from .forms import VehicleForm, VehicleEditForm


def index(request):
    vehicles = Vehicle.objects.all()
    return render(request, 'vehiclemanager/vehicle_list.html', {'vehicles': vehicles})


def edit_vehicle(request, vehicle_id):
    BatteryFormSet = inlineformset_factory(Vehicle, Battery, fields=('is_on',), extra=0)

    vehicle = get_object_or_404(Vehicle, id=vehicle_id)

    if request.method == "POST":
        form = VehicleEditForm(request.POST, instance=vehicle)
        bform = BatteryFormSet(request.POST, instance=vehicle)
        vehicle.add_batteries(int(request.POST['addbats']))
        if form.is_valid():
            form.save()
            bform.save()
            return HttpResponseRedirect('/')

    else:
        form = VehicleEditForm(instance=vehicle)

    vehicle = get_object_or_404(Vehicle, id=vehicle_id)

    bformset = BatteryFormSet(instance=vehicle)

    return render(request, 'vehiclemanager/edit_vehicle.html',
                  {'vehicle': vehicle, 'form': form.as_p(), 'bformset': bformset})


def add_vehicle(request):
    if request.method == 'POST':
        form = VehicleForm(request.POST)
        if form.is_valid():
            form.save()

            vehicle = Vehicle.objects.get(id=form.cleaned_data['id'])
            vehicle.add_batteries(form.cleaned_data['batteries'])

            return HttpResponseRedirect('/')

    else:
        form = VehicleForm()

    return render(request, 'vehiclemanager/add_vehicle.html', {'form': form.as_p()})


def delete_vehicle(request, vehicle_id):
    vehicle = get_object_or_404(Vehicle, id=vehicle_id)
    batteries = Battery.objects.filter(vehicle=vehicle)
    batteries.delete()
    vehicle.delete()
    return HttpResponseRedirect('/')

vehiclemanager/templates/vehiclemanager/add_vehicle.html
{% extends 'vehiclemanager/base.html' %}

{% block content %}
    <h1>Dodaj nowy pojazd</h1>
    <form action={% url 'add_vehicle' %} method="post">
        <table class="form-table">
            {% csrf_token %}
            {{ form }}</table>
        <button class="button" type="submit">Zapisz</button>
        <a class="button bt-delete" href={% url 'index' %}>Anuluj</a>
    </form>

{% endblock %}

vehiclemanager/templates/vehiclemanager/base.html
{% load static %}
<link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet">
<link rel='stylesheet' href="{% static 'css/app.css' %}">
<div class="container">
    <div class="main-content rounded-box">
        {% block content %}
        {% endblock %}
    </div>
    <span class="credits">Leszek Kicior 2018</span>
</div>

vehiclemanager/templates/vehiclemanager/edit_vehicle.html
{% extends "vehiclemanager/base.html" %}

<div class="edit-vehicle">
    {% block content %}
        <h1>Edytuj pojazd</h1>
        <form action={% url 'edit_vehicle' vehicle_id=vehicle.id %} method="post">
            {% csrf_token %}

            {{ form }}
            {{ bformset.management_form }}
            {% if bformset.instance.battery_set.count %}
            <h3>Baterie</h3>
            <div class="battery-list rounded-box">

                {% for b in bformset %}
                    <div class="battery-info">
                        <h2>{{ b.instance.battery_number }}</h2>
                        <div>
                            <div class="label-switch">Aktywna:
                                <label class="switch">
                                    {{ b.is_on }}
                                    <span class="slider round"></span>
                                </label></div>
                            <div class="label-switch">Usuń:
                                <label class="switch">
                                    {{ b.DELETE }}
                                    <span class="slider delete round"></span>
                                </label>
                            </div>
                        </div>

                        {{ b.vehicle }}{{ b.id }}
                    </div>
                    <br>
                {% endfor %}
            </div>
        {% endif %}
            <div><label>Dodaj baterie:</label>
                <input type="number" name="addbats" value="0"/>
            </div>
            <div style="margin-top:20px;">
                <button class="button" type="submit">Zapisz</button>
                <a class="button bt-delete" href={% url 'index' %}>Anuluj</a>
            </div>

        </form>
    {% endblock %}
</div>

vehiclemanager/templates/vehiclemanager/vehicle_list.html
{% extends 'vehiclemanager/base.html' %}

{% block content %}
    <a class='button' href={% url 'add_vehicle' %}>Dodaj pojazd</a>

    {% if vehicles %}
        <div class="vehicle-list">

            {% for vehicle in vehicles %}
                <div class="vehicle rounded-box">
                    <div class="vehicle-info"><p>ID: {{ vehicle.id }}</p>
                        <h2> {{ vehicle.name }}</h2>
                        <p><b>Liczba baterii: </b> {{ vehicle.battery_number }}</p>
                    </div>
                    <div class="button-container">
                        <a class="button" href={% url 'edit_vehicle' vehicle_id=vehicle.id %}>Edytuj</a>
                        <a class="button bt-delete" href={% url 'delete_vehicle' vehicle_id=vehicle.id %}>Usuń</a>
                    </div>
                </div>
            {% endfor %}


            {% else %}
            <div class="info">
                <p>Nie dodałeś jeszcze żadnych pojazdów!</p>
            </div>
        </div>
    {% endif %}
{% endblock %}